.TH "Attachments" 3 "Fri Dec 18 2020" "Mass Mailing Using C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Attachments
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBody\fP\&.
.PP
Inherited by \fBMails\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBgetSameAttachToAll\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBno_of_attachments\fP"
.br
.ti -1c
.RI "char \fByour_attachments\fP [100][50]"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void Attachments::getSameAttachToAll ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int Attachments::no_of_attachments\fC [protected]\fP"

.SS "char Attachments::your_attachments[100][50]\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Mass Mailing Using C++ from the source code\&.
