.TH "Body" 3 "Fri Dec 18 2020" "Mass Mailing Using C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Body
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSubject\fP\&.
.PP
Inherited by \fBAttachments\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBshowbody\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "char \fByour_body\fP [100000]"
.br
.ti -1c
.RI "char \fBch\fP"
.br
.ti -1c
.RI "int \fBchoice_body\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void Body::showbody ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "char Body::ch\fC [protected]\fP"

.SS "int Body::choice_body\fC [protected]\fP"

.SS "char Body::your_body[100000]\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Mass Mailing Using C++ from the source code\&.
