.TH "LogIn" 3 "Fri Dec 18 2020" "Mass Mailing Using C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LogIn
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFrontPage\fP\&.
.PP
Inherited by \fBRecipients\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBshowheader\fP ()"
.br
.ti -1c
.RI "void \fBgetaddress\fP ()"
.br
.ti -1c
.RI "void \fBgetpass\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "char \fByour_address\fP [100]"
.br
.ti -1c
.RI "char \fByour_password\fP [50]"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void LogIn::getaddress ()\fC [inline]\fP"

.SS "void LogIn::getpass ()\fC [inline]\fP"

.SS "void LogIn::showheader ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "char LogIn::your_address[100]\fC [protected]\fP"

.SS "char LogIn::your_password[50]\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Mass Mailing Using C++ from the source code\&.
