.TH "G:/1. Mass Mailing System/1. code working/Mass Mailing using CPP_Amazing/sending_mails_using-_CPP/mailing.cpp" 3 "Fri Dec 18 2020" "Mass Mailing Using C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
G:/1. Mass Mailing System/1. code working/Mass Mailing using CPP_Amazing/sending_mails_using-_CPP/mailing.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'C:\\vcpkg\\downloads\\tools\\perl\\5\&.30\&.0\&.1\\c\\lib\\gcc\\i686\-w64\-mingw32\\8\&.3\&.0\\include\\stdfix\&.h'\fP
.br
\fC#include <tchar\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <conio\&.h>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include 'EASendMailObj\&.tlh'\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFrontPage\fP"
.br
.ti -1c
.RI "class \fBLogIn\fP"
.br
.ti -1c
.RI "class \fBRecipients\fP"
.br
.ti -1c
.RI "class \fBSubject\fP"
.br
.ti -1c
.RI "class \fBBody\fP"
.br
.ti -1c
.RI "class \fBAttachments\fP"
.br
.ti -1c
.RI "class \fBMails\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBODY_LOCATION\fP   'G:\\\\1\&. Mass Mailing System\\\\1\&. code working\\\\sending_mails_using\-_CPP\\\\body\&.html'"
.br
.ti -1c
.RI "#define \fBsize_recipients\fP   1000"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBConnectNormal\fP = 0"
.br
.ti -1c
.RI "const int \fBConnectSSLAuto\fP = 1"
.br
.ti -1c
.RI "const int \fBConnectSTARTTLS\fP = 2"
.br
.ti -1c
.RI "const int \fBConnectDirectSSL\fP = 3"
.br
.ti -1c
.RI "const int \fBConnectTryTLS\fP = 4"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BODY_LOCATION   'G:\\\\1\&. Mass Mailing System\\\\1\&. code working\\\\sending_mails_using\-_CPP\\\\body\&.html'"

.SS "#define size_recipients   1000"

.SH "Function Documentation"
.PP 
.SS "int main ()"

.SH "Variable Documentation"
.PP 
.SS "const int ConnectDirectSSL = 3"

.SS "const int ConnectNormal = 0"

.SS "const int ConnectSSLAuto = 1"

.SS "const int ConnectSTARTTLS = 2"

.SS "const int ConnectTryTLS = 4"

.SH "Author"
.PP 
Generated automatically by Doxygen for Mass Mailing Using C++ from the source code\&.
