.TH "Recipients" 3 "Fri Dec 18 2020" "Mass Mailing Using C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Recipients
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLogIn\fP\&.
.PP
Inherited by \fBSubject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBgetrecipient\fP ()"
.br
.ti -1c
.RI "void \fBshowrecipient\fP ()"
.br
.ti -1c
.RI "void \fBshowrecipientVar\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBno_of_recipients\fP"
.br
.ti -1c
.RI "int \fBlist_choice\fP"
.br
.ti -1c
.RI "int \fBconsoleOrfile\fP"
.br
.ti -1c
.RI "char \fBrecipients\fP [1000][50]"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void Recipients::getrecipient ()\fC [inline]\fP"

.SS "void Recipients::showrecipient ()\fC [inline]\fP"

.SS "void Recipients::showrecipientVar ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int Recipients::consoleOrfile\fC [protected]\fP"

.SS "int Recipients::list_choice\fC [protected]\fP"

.SS "int Recipients::no_of_recipients\fC [protected]\fP"

.SS "char Recipients::recipients[1000][50]\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Mass Mailing Using C++ from the source code\&.
