.TH "Subject" 3 "Fri Dec 18 2020" "Mass Mailing Using C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Subject
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRecipients\fP\&.
.PP
Inherited by \fBBody\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBgetsubject\fP ()"
.br
.ti -1c
.RI "void \fBshowsubject\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "char \fByour_subject\fP [100]"
.br
.ti -1c
.RI "char \fBsubject\fP [100]"
.br
.ti -1c
.RI "char \fBch\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void Subject::getsubject ()\fC [inline]\fP"

.SS "void Subject::showsubject ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "char Subject::ch\fC [protected]\fP"

.SS "char Subject::subject[100]\fC [protected]\fP"

.SS "char Subject::your_subject[100]\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Mass Mailing Using C++ from the source code\&.
